### PR TITLE
Add 'insecure' option to enforce use of HTTP protocol for registry requests

### PR DESCRIPTION
**Pull request by KanagawaNezumi**
#76

### CODE REVIEW

**Comment by roman-vynar** [comment]
Thanks!

However, whatever I do to test this it does not have any effect. It still tries https. Moreover, it tries https and then http even w/o that option. May be because I am on mac...

**Comment by KanagawaNezumi** [comment]
That's a bit strange. Did you set registry.insecure to true when you were testing?

**Comment by roman-vynar** [comment]
Yes. Can you reliably test this on your end?

**Comment by roman-vynar** [comment]
Ok, the code is working despite it will still try https first no matter what in case it is available. Otherwise, http.

**Comment by KanagawaNezumi** [comment]
😂Strangely, it works quite well on my end. I previously tested it on Windows and Debian systems, and it worked as expected. I just tested it on an Intel CPU Mac: if registry.insecure is set to false, the program throws an exception 'http: server gave HTTP response to HTTPS client' and then exits. If set to true, it connects successfully.

**Pull request merged**
