### PR TITLE
Add tag creation date in tags view

### PR DESCRIPTION
**Pull request by rmwpl**
This branch introduces a second column -- tag creation date -- in the tags view.

### CODE REVIEW

**Comment by rmwpl** [comment]
Well, it's the first piece of code I've ever written in Go, so for sure it can be done better! :)

**Comment by roman-vynar** [comment]
We have hundreds of tags and I think it will be not efficient. There is probably no way to make it fast and efficient because the only way to get `created` is to make an API request for each tag info.

**Comment by rmwpl** [comment]
Yup, same here, that's why after some experimentation, I've put it in the background.

**Comment by BouweCeunen** [comment]
Is it possible to implement this with a flag? So that users can decide whether they want the creation date and don't mind the performance penalty.

**Comment by roman-vynar** [comment]
We have made a full rewrite and I can say for sure, it's still impossible to make it properly because of the way the registry is designed. It does not have an API to fetch this efficiently. By iterating everything makes sense only when purging tags.

**Pull request closed without merging**
